"""Initial migration from SQL schema

Revision ID: 0d3dc62babce
Revises: 
Create Date: 2024-11-03 20:25:29.456337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3dc62babce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Facultate',
    sa.Column('id_Facultate', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nume', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_Facultate')
    )
    op.create_table('Profesor',
    sa.Column('id_Profesor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nume', sa.VARCHAR(length=50), nullable=False),
    sa.Column('prenume', sa.VARCHAR(length=50), nullable=False),
    sa.Column('grad', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id_Facultate', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('parola', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_Facultate'], ['Facultate.id_Facultate'], ),
    sa.PrimaryKeyConstraint('id_Profesor'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Student',
    sa.Column('id_Student', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nume', sa.VARCHAR(length=50), nullable=False),
    sa.Column('prenume', sa.VARCHAR(length=50), nullable=False),
    sa.Column('grupa', sa.VARCHAR(length=10), nullable=False),
    sa.Column('id_Facultate', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('parola', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_Facultate'], ['Facultate.id_Facultate'], ),
    sa.PrimaryKeyConstraint('id_Student'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Materie',
    sa.Column('id_Materie', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nume', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id_Profesor', sa.Integer(), nullable=False),
    sa.Column('tip_examen', sa.VARCHAR(length=50), nullable=True),
    sa.Column('an_studiu', sa.Integer(), nullable=False),
    sa.Column('semestru', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_Profesor'], ['Profesor.id_Profesor'], ),
    sa.PrimaryKeyConstraint('id_Materie')
    )
    op.create_table('Cerere',
    sa.Column('id_Cerere', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_Profesor', sa.Integer(), nullable=False),
    sa.Column('id_Facultate', sa.Integer(), nullable=False),
    sa.Column('id_Materie', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_Facultate'], ['Facultate.id_Facultate'], ),
    sa.ForeignKeyConstraint(['id_Materie'], ['Materie.id_Materie'], ),
    sa.ForeignKeyConstraint(['id_Profesor'], ['Profesor.id_Profesor'], ),
    sa.PrimaryKeyConstraint('id_Cerere')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cerere')
    op.drop_table('Materie')
    op.drop_table('Student')
    op.drop_table('Profesor')
    op.drop_table('Facultate')
    # ### end Alembic commands ###
