"""Initial migration from SQL schema

Revision ID: 7140491246e1
Revises: 9200dc26ff81
Create Date: 2024-11-04 21:52:21.562443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7140491246e1'
down_revision: Union[str, None] = '9200dc26ff81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Facultate_Profesor',
    sa.Column('id_Facultate', sa.Integer(), nullable=False),
    sa.Column('id_Profesor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_Facultate'], ['Facultate.id_Facultate'], ),
    sa.ForeignKeyConstraint(['id_Profesor'], ['Profesor.id_Profesor'], ),
    sa.PrimaryKeyConstraint('id_Facultate', 'id_Profesor')
    )
    op.create_table('Asistent_Examen',
    sa.Column('id_Examen', sa.Integer(), nullable=False),
    sa.Column('id_Profesor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_Examen'], ['Examen.id_Examen'], ),
    sa.ForeignKeyConstraint(['id_Profesor'], ['Profesor.id_Profesor'], ),
    sa.PrimaryKeyConstraint('id_Examen', 'id_Profesor')
    )
    op.create_table('Grupa_Examen',
    sa.Column('id_Examen', sa.Integer(), nullable=False),
    sa.Column('grupa', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_Examen'], ['Examen.id_Examen'], ),
    sa.PrimaryKeyConstraint('id_Examen', 'grupa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Grupa_Examen')
    op.drop_table('Asistent_Examen')
    op.drop_table('Facultate_Profesor')
    # ### end Alembic commands ###
